package awesomenes


var instrs = []*instr {
  &instr{ name: "ADC", opcode: 0x69, size: 2, cycles: 2, fn: adc, addrMode: AddrModeImmediate, },
  &instr{ name: "ADC", opcode: 0x65, size: 2, cycles: 3, fn: adc, addrMode: AddrModeZeroPage, },
  &instr{ name: "ADC", opcode: 0x75, size: 2, cycles: 4, fn: adc, addrMode: AddrModeZeroX, },
  &instr{ name: "ADC", opcode: 0x6d, size: 3, cycles: 4, fn: adc, addrMode: AddrModeAbs, },
  &instr{ name: "ADC", opcode: 0x7d, size: 3, cycles: 4, fn: adc, addrMode: AddrModeAbsX, },
  &instr{ name: "ADC", opcode: 0x79, size: 3, cycles: 4, fn: adc, addrMode: AddrModeAbsY, },
  &instr{ name: "ADC", opcode: 0x61, size: 2, cycles: 6, fn: adc, addrMode: AddrModeXIndirect, },
  &instr{ name: "ADC", opcode: 0x71, size: 2, cycles: 5, fn: adc, addrMode: AddrModeIndirectY, },

  &instr{ name: "AND", opcode: 0x29, size: 2, cycles: 2, fn: and, addrMode: AddrModeImmediate, },
  &instr{ name: "AND", opcode: 0x25, size: 2, cycles: 3, fn: and, addrMode: AddrModeZeroPage, },
  &instr{ name: "AND", opcode: 0x35, size: 2, cycles: 4, fn: and, addrMode: AddrModeZeroX, },
  &instr{ name: "AND", opcode: 0x2d, size: 3, cycles: 4, fn: and, addrMode: AddrModeAbs, },
  &instr{ name: "AND", opcode: 0x3d, size: 3, cycles: 4, fn: and, addrMode: AddrModeAbsX, },
  &instr{ name: "AND", opcode: 0x39, size: 3, cycles: 4, fn: and, addrMode: AddrModeAbsY, },
  &instr{ name: "AND", opcode: 0x21, size: 2, cycles: 6, fn: and, addrMode: AddrModeXIndirect, },
  &instr{ name: "AND", opcode: 0x31, size: 2, cycles: 5, fn: and, addrMode: AddrModeIndirectY, },

  &instr{ name: "ASL", opcode: 0x0a, size: 1, cycles: 2, fn: asl, addrMode: AddrModeAccumulator, },
  &instr{ name: "ASL", opcode: 0x06, size: 2, cycles: 5, fn: asl, addrMode: AddrModeZeroPage, },
  &instr{ name: "ASL", opcode: 0x16, size: 2, cycles: 6, fn: asl, addrMode: AddrModeZeroX, },
  &instr{ name: "ASL", opcode: 0x0e, size: 3, cycles: 6, fn: asl, addrMode: AddrModeAbs, },
  &instr{ name: "ASL", opcode: 0x1e, size: 3, cycles: 7, fn: asl, addrMode: AddrModeAbsX, },

  &instr{ name: "BCC", opcode: 0x90, size: 2, cycles: 2, fn: bcc, addrMode: AddrModeRelative, },
  &instr{ name: "BCS", opcode: 0xb0, size: 2, cycles: 2, fn: bcs, addrMode: AddrModeRelative, },
  &instr{ name: "BEQ", opcode: 0xf0, size: 2, cycles: 2, fn: beq, addrMode: AddrModeRelative, },

  &instr{ name: "BIT", opcode: 0x24, size: 2, cycles: 3, fn: bit, addrMode: AddrModeZeroPage, },
  &instr{ name: "BIT", opcode: 0x2c, size: 3, cycles: 4, fn: bit, addrMode: AddrModeAbs, },

  &instr{ name: "BMI", opcode: 0x30, size: 2, cycles: 2, fn: bmi, addrMode: AddrModeRelative, },
  &instr{ name: "BNE", opcode: 0xd0, size: 2, cycles: 2, fn: bne, addrMode: AddrModeRelative, },
  &instr{ name: "BPL", opcode: 0x10, size: 2, cycles: 2, fn: bpl, addrMode: AddrModeRelative, },
  &instr{ name: "BRK", opcode: 0x00, size: 1, cycles: 7, fn: brk, addrMode: AddrModeImplied, },
  &instr{ name: "BVC", opcode: 0x50, size: 2, cycles: 2, fn: bvc, addrMode: AddrModeRelative, },
  &instr{ name: "BVS", opcode: 0x70, size: 2, cycles: 2, fn: bvc, addrMode: AddrModeRelative, },

  &instr{ name: "CLC", opcode: 0x18, size: 1, cycles: 2, fn: clc, addrMode: AddrModeImplied, },
  &instr{ name: "CLD", opcode: 0xd8, size: 1, cycles: 2, fn: cld, addrMode: AddrModeImplied, },
  &instr{ name: "CLI", opcode: 0x58, size: 1, cycles: 2, fn: cli, addrMode: AddrModeImplied, },
  &instr{ name: "CLV", opcode: 0xb8, size: 1, cycles: 2, fn: clv, addrMode: AddrModeImplied, },

  &instr{ name: "CMP", opcode: 0xc9, size: 2, cycles: 2, fn: cmp, addrMode: AddrModeImmediate, },
  &instr{ name: "CMP", opcode: 0xc5, size: 2, cycles: 3, fn: cmp, addrMode: AddrModeZeroPage, },
  &instr{ name: "CMP", opcode: 0xd5, size: 2, cycles: 4, fn: cmp, addrMode: AddrModeZeroX, },
  &instr{ name: "CMP", opcode: 0xcd, size: 3, cycles: 4, fn: cmp, addrMode: AddrModeAbs, },
  &instr{ name: "CMP", opcode: 0xdd, size: 3, cycles: 4, fn: cmp, addrMode: AddrModeAbsX, },
  &instr{ name: "CMP", opcode: 0xd9, size: 3, cycles: 4, fn: cmp, addrMode: AddrModeAbsY, },
  &instr{ name: "CMP", opcode: 0xc1, size: 2, cycles: 6, fn: cmp, addrMode: AddrModeXIndirect, },
  &instr{ name: "CMP", opcode: 0xd1, size: 2, cycles: 5, fn: cmp, addrMode: AddrModeIndirectY, },
  &instr{ name: "CPX", opcode: 0xe0, size: 2, cycles: 2, fn: cpx, addrMode: AddrModeImmediate, },
  &instr{ name: "CPX", opcode: 0xe4, size: 2, cycles: 3, fn: cpx, addrMode: AddrModeZeroPage, },
  &instr{ name: "CPX", opcode: 0xec, size: 3, cycles: 4, fn: cpx, addrMode: AddrModeAbs, },
  &instr{ name: "CPY", opcode: 0xc0, size: 2, cycles: 2, fn: cpy, addrMode: AddrModeImmediate, },
  &instr{ name: "CPY", opcode: 0xc4, size: 2, cycles: 3, fn: cpy, addrMode: AddrModeZeroPage, },
  &instr{ name: "CPY", opcode: 0xcc, size: 3, cycles: 4, fn: cpy, addrMode: AddrModeAbs, },

  &instr{ name: "DEC", opcode: 0xc6, size: 2, cycles: 5, fn: dec, addrMode: AddrModeZeroPage, },
  &instr{ name: "DEC", opcode: 0xd6, size: 2, cycles: 6, fn: dec, addrMode: AddrModeZeroX, },
  &instr{ name: "DEC", opcode: 0xce, size: 3, cycles: 6, fn: dec, addrMode: AddrModeAbs, },
  &instr{ name: "DEC", opcode: 0xde, size: 3, cycles: 7, fn: dec, addrMode: AddrModeAbsX, },
  &instr{ name: "DEX", opcode: 0xca, size: 1, cycles: 2, fn: dex, addrMode: AddrModeImplied, },
  &instr{ name: "DEY", opcode: 0x88, size: 1, cycles: 2, fn: dey, addrMode: AddrModeImplied, },

  &instr{ name: "EOR", opcode: 0x49, size: 2, cycles: 2, fn: eor, addrMode: AddrModeImmediate, },
  &instr{ name: "EOR", opcode: 0x45, size: 2, cycles: 3, fn: eor, addrMode: AddrModeZeroPage, },
  &instr{ name: "EOR", opcode: 0x55, size: 2, cycles: 4, fn: eor, addrMode: AddrModeZeroX, },
  &instr{ name: "EOR", opcode: 0x4d, size: 3, cycles: 4, fn: eor, addrMode: AddrModeAbs, },
  &instr{ name: "EOR", opcode: 0x5d, size: 3, cycles: 4, fn: eor, addrMode: AddrModeAbsX, },
  &instr{ name: "EOR", opcode: 0x59, size: 3, cycles: 4, fn: eor, addrMode: AddrModeAbsY, },
  &instr{ name: "EOR", opcode: 0x41, size: 2, cycles: 6, fn: eor, addrMode: AddrModeXIndirect, },
  &instr{ name: "EOR", opcode: 0x51, size: 2, cycles: 5, fn: eor, addrMode: AddrModeIndirectY, },

  &instr{ name: "INC", opcode: 0xe6, size: 2, cycles: 5, fn: inc, addrMode: AddrModeZeroPage, },
  &instr{ name: "INC", opcode: 0xf6, size: 2, cycles: 6, fn: inc, addrMode: AddrModeZeroX, },
  &instr{ name: "INC", opcode: 0xee, size: 3, cycles: 6, fn: inc, addrMode: AddrModeAbs, },
  &instr{ name: "INC", opcode: 0xfe, size: 3, cycles: 7, fn: inc, addrMode: AddrModeAbsX, },
  &instr{ name: "INX", opcode: 0xe8, size: 1, cycles: 2, fn: inx, addrMode: AddrModeImplied, },
  &instr{ name: "INY", opcode: 0xc8, size: 1, cycles: 2, fn: iny, addrMode: AddrModeImplied, },

  &instr{ name: "JMP", opcode: 0x4c, size: 3, cycles: 3, fn: jmp, addrMode: AddrModeAbs, },
  &instr{ name: "JMP", opcode: 0x6c, size: 3, cycles: 5, fn: jmp, addrMode: AddrModeIndirect, },
  &instr{ name: "JSR", opcode: 0x20, size: 3, cycles: 6, fn: jsr, addrMode: AddrModeAbs, },

  &instr{ name: "LDA", opcode: 0xa9, size: 2, cycles: 2, fn: lda, addrMode: AddrModeImmediate, },
  &instr{ name: "LDA", opcode: 0xa5, size: 2, cycles: 3, fn: lda, addrMode: AddrModeZeroPage, },
  &instr{ name: "LDA", opcode: 0xb5, size: 2, cycles: 4, fn: lda, addrMode: AddrModeZeroX, },
  &instr{ name: "LDA", opcode: 0xad, size: 3, cycles: 4, fn: lda, addrMode: AddrModeAbs, },
  &instr{ name: "LDA", opcode: 0xbd, size: 3, cycles: 4, fn: lda, addrMode: AddrModeAbsX, },
  &instr{ name: "LDA", opcode: 0xb9, size: 3, cycles: 4, fn: lda, addrMode: AddrModeAbsY, },
  &instr{ name: "LDA", opcode: 0xa1, size: 2, cycles: 6, fn: lda, addrMode: AddrModeXIndirect, },
  &instr{ name: "LDA", opcode: 0xb1, size: 2, cycles: 5, fn: lda, addrMode: AddrModeIndirectY, },
  &instr{ name: "LDX", opcode: 0xa2, size: 2, cycles: 2, fn: ldx, addrMode: AddrModeImmediate, },
  &instr{ name: "LDX", opcode: 0xa6, size: 2, cycles: 3, fn: ldx, addrMode: AddrModeZeroPage, },
  &instr{ name: "LDX", opcode: 0xb6, size: 2, cycles: 4, fn: ldx, addrMode: AddrModeZeroY, },
  &instr{ name: "LDX", opcode: 0xae, size: 3, cycles: 4, fn: ldx, addrMode: AddrModeAbs, },
  &instr{ name: "LDX", opcode: 0xbe, size: 3, cycles: 4, fn: ldx, addrMode: AddrModeAbsY, },
  &instr{ name: "LDY", opcode: 0xa0, size: 2, cycles: 2, fn: ldy, addrMode: AddrModeImmediate, },
  &instr{ name: "LDY", opcode: 0xa4, size: 2, cycles: 3, fn: ldy, addrMode: AddrModeZeroPage, },
  &instr{ name: "LDY", opcode: 0xb4, size: 2, cycles: 4, fn: ldy, addrMode: AddrModeZeroX, },
  &instr{ name: "LDY", opcode: 0xac, size: 3, cycles: 4, fn: ldy, addrMode: AddrModeAbs, },
  &instr{ name: "LDY", opcode: 0xbc, size: 3, cycles: 4, fn: ldy, addrMode: AddrModeAbsX, },

  &instr{ name: "LSR", opcode: 0x4a, size: 1, cycles: 2, fn: lsr, addrMode: AddrModeAccumulator, },
  &instr{ name: "LSR", opcode: 0x46, size: 2, cycles: 5, fn: lsr, addrMode: AddrModeZeroPage, },
  &instr{ name: "LSR", opcode: 0x56, size: 2, cycles: 6, fn: lsr, addrMode: AddrModeZeroX, },
  &instr{ name: "LSR", opcode: 0x4e, size: 3, cycles: 6, fn: lsr, addrMode: AddrModeAbs, },
  &instr{ name: "LSR", opcode: 0x53, size: 3, cycles: 7, fn: lsr, addrMode: AddrModeAbsX, },

  &instr{ name: "NOP", opcode: 0xea, size: 1, cycles: 2, fn: nop, addrMode: AddrModeImplied, },

  &instr{ name: "ORA", opcode: 0x09, size: 2, cycles: 2, fn: ora, addrMode: AddrModeImmediate, },
  &instr{ name: "ORA", opcode: 0x05, size: 2, cycles: 3, fn: ora, addrMode: AddrModeZeroPage, },
  &instr{ name: "ORA", opcode: 0x15, size: 2, cycles: 4, fn: ora, addrMode: AddrModeZeroX, },
  &instr{ name: "ORA", opcode: 0x0d, size: 3, cycles: 4, fn: ora, addrMode: AddrModeAbs, },
  &instr{ name: "ORA", opcode: 0x1d, size: 3, cycles: 4, fn: ora, addrMode: AddrModeAbsX, },
  &instr{ name: "ORA", opcode: 0x19, size: 3, cycles: 4, fn: ora, addrMode: AddrModeAbsY, },
  &instr{ name: "ORA", opcode: 0x01, size: 2, cycles: 6, fn: ora, addrMode: AddrModeXIndirect, },
  &instr{ name: "ORA", opcode: 0x11, size: 2, cycles: 5, fn: ora, addrMode: AddrModeIndirectY, },

  &instr{ name: "PHA", opcode: 0x48, size: 1, cycles: 3, fn: pha, addrMode: AddrModeImplied, },
  &instr{ name: "PHP", opcode: 0x08, size: 1, cycles: 3, fn: php, addrMode: AddrModeImplied, },
  &instr{ name: "PLA", opcode: 0x68, size: 1, cycles: 4, fn: pla, addrMode: AddrModeImplied, },
  &instr{ name: "PLP", opcode: 0x28, size: 1, cycles: 4, fn: plp, addrMode: AddrModeImplied, },

  &instr{ name: "ROL", opcode: 0x2a, size: 1, cycles: 2, fn: rol, addrMode: AddrModeAccumulator, },
  &instr{ name: "ROL", opcode: 0x26, size: 2, cycles: 5, fn: rol, addrMode: AddrModeZeroPage, },
  &instr{ name: "ROL", opcode: 0x36, size: 2, cycles: 6, fn: rol, addrMode: AddrModeZeroX, },
  &instr{ name: "ROL", opcode: 0x2e, size: 3, cycles: 6, fn: rol, addrMode: AddrModeAbs, },
  &instr{ name: "ROL", opcode: 0x3e, size: 3, cycles: 7, fn: rol, addrMode: AddrModeAbsX, },
  &instr{ name: "ROR", opcode: 0x6a, size: 1, cycles: 2, fn: ror, addrMode: AddrModeAccumulator, },
  &instr{ name: "ROR", opcode: 0x66, size: 2, cycles: 5, fn: ror, addrMode: AddrModeZeroPage, },
  &instr{ name: "ROR", opcode: 0x76, size: 2, cycles: 6, fn: ror, addrMode: AddrModeZeroX, },
  &instr{ name: "ROR", opcode: 0x6e, size: 3, cycles: 6, fn: ror, addrMode: AddrModeAbs, },
  &instr{ name: "ROR", opcode: 0x7e, size: 3, cycles: 7, fn: ror, addrMode: AddrModeAbsX, },
  &instr{ name: "RTI", opcode: 0x40, size: 1, cycles: 6, fn: rti, addrMode: AddrModeImplied, },
  &instr{ name: "RTS", opcode: 0x60, size: 1, cycles: 6, fn: rts, addrMode: AddrModeImplied, },

  &instr{ name: "SBC", opcode: 0xe9, size: 2, cycles: 2, fn: sbc, addrMode: AddrModeImmediate, },
  &instr{ name: "SBC", opcode: 0xe5, size: 2, cycles: 3, fn: sbc, addrMode: AddrModeZeroPage, },
  &instr{ name: "SBC", opcode: 0xf5, size: 2, cycles: 4, fn: sbc, addrMode: AddrModeZeroX, },
  &instr{ name: "SBC", opcode: 0xed, size: 3, cycles: 4, fn: sbc, addrMode: AddrModeAbs, },
  &instr{ name: "SBC", opcode: 0xfd, size: 3, cycles: 4, fn: sbc, addrMode: AddrModeAbsX, },
  &instr{ name: "SBC", opcode: 0xf9, size: 3, cycles: 4, fn: sbc, addrMode: AddrModeAbsY, },
  &instr{ name: "SBC", opcode: 0xe1, size: 2, cycles: 6, fn: sbc, addrMode: AddrModeXIndirect, },
  &instr{ name: "SBC", opcode: 0xf1, size: 2, cycles: 5, fn: sbc, addrMode: AddrModeIndirectY, },

  &instr{ name: "SEC", opcode: 0x38, size: 1, cycles: 2, fn: sec, addrMode: AddrModeImplied, },
  &instr{ name: "SED", opcode: 0xf8, size: 1, cycles: 2, fn: sed, addrMode: AddrModeImplied, },
  &instr{ name: "SEI", opcode: 0x78, size: 1, cycles: 2, fn: sei, addrMode: AddrModeImplied, },

  &instr{ name: "STA", opcode: 0x85, size: 2, cycles: 3, fn: sta, addrMode: AddrModeZeroPage, },
  &instr{ name: "STA", opcode: 0x95, size: 2, cycles: 4, fn: sta, addrMode: AddrModeZeroX, },
  &instr{ name: "STA", opcode: 0x8d, size: 3, cycles: 4, fn: sta, addrMode: AddrModeAbs, },
  &instr{ name: "STA", opcode: 0x9d, size: 3, cycles: 5, fn: sta, addrMode: AddrModeAbsX, },
  &instr{ name: "STA", opcode: 0x99, size: 3, cycles: 5, fn: sta, addrMode: AddrModeAbsY, },
  &instr{ name: "STA", opcode: 0x81, size: 2, cycles: 6, fn: sta, addrMode: AddrModeXIndirect, },
  &instr{ name: "STA", opcode: 0x91, size: 2, cycles: 6, fn: sta, addrMode: AddrModeIndirectY, },

  &instr{ name: "STX", opcode: 0x86, size: 2, cycles: 3, fn: stx, addrMode: AddrModeZeroPage, },
  &instr{ name: "STX", opcode: 0x96, size: 2, cycles: 4, fn: stx, addrMode: AddrModeZeroY, },
  &instr{ name: "STX", opcode: 0x8e, size: 3, cycles: 4, fn: stx, addrMode: AddrModeAbs, },

  &instr{ name: "STY", opcode: 0x84, size: 2, cycles: 3, fn: stx, addrMode: AddrModeZeroPage, },
  &instr{ name: "STY", opcode: 0x94, size: 2, cycles: 4, fn: stx, addrMode: AddrModeZeroX, },
  &instr{ name: "STY", opcode: 0x8c, size: 3, cycles: 4, fn: stx, addrMode: AddrModeAbs, },

  &instr{ name: "TAX", opcode: 0xaa, size: 1, cycles: 2, fn: tax, addrMode: AddrModeImplied, },
  &instr{ name: "TAY", opcode: 0xa8, size: 1, cycles: 2, fn: tay, addrMode: AddrModeImplied, },
  &instr{ name: "TSX", opcode: 0xba, size: 1, cycles: 2, fn: tsx, addrMode: AddrModeImplied, },
  &instr{ name: "TXA", opcode: 0x8a, size: 1, cycles: 2, fn: txa, addrMode: AddrModeImplied, },
  &instr{ name: "TXS", opcode: 0x9a, size: 1, cycles: 2, fn: txs, addrMode: AddrModeImplied, },
  &instr{ name: "TYA", opcode: 0x98, size: 1, cycles: 2, fn: tya, addrMode: AddrModeImplied, },
}
